[setup]
asofDate = "2016-02-05"
inputPath = "input_bundle/vre_amc"
outputPath = "Output"
logFile = "log.txt"
logMask = "15"
marketDataFile = "market.txt"
fixingDataFile = "fixings.txt"
implyTodaysFixings = "N"
curveConfigFile = "runtime_policy/resolved_curve_configuration.json"
conventionsFile = "reference_registry/convention_manifest.json"
marketConfigFile = "runtime_policy/resolved_todays_market.json"
pricingEnginesFile = "runtime_policy/pricingengine/resolved_pricing_policy.json"
portfolioFile = "portfolio.xml"
observationModel = "None"
continueOnError = "false"
calendarAdjustment = "runtime_policy/resolved_calendar_adjustments_manifest.json"
currencyConfiguration = "runtime_policy/resolved_currency_registry.json"
nThreads = "1"

[markets]
lgmcalibration = "libor"
fxcalibration = "libor"
eqcalibration = "libor"
pricing = "libor"
simulation = "libor"

[analytics]
[analytics.npv]
active = "Y"
baseCurrency = "EUR"
outputFileName = "npv.csv"

[analytics.simulation]
active = "Y"
amc = "Y"
amcTradeTypes = "Swap,Swaption,FxOption"
simulationConfigFile = "runtime_policy/resolved_simulation.json"
pricingEnginesFile = "runtime_policy/pricingengine/resolved_pricing_policy.json"
amcPricingEnginesFile = "runtime_policy/pricingengine_amc/resolved_pricing_policy.json"
baseCurrency = "EUR"
storeScenarios = "N"

[analytics.xva]
active = "Y"
csaFile = "runtime_policy/resolved_netting_set_information.json"
baseCurrency = "EUR"
exposureProfiles = "Y"
exposureProfilesByTrade = "Y"
quantile = "0.95"
calculationType = "NoLag"
allocationMethod = "None"
