[setup]
asofDate = "2016-02-05"
inputPath = "input_bundle/vre_dim"
outputPath = "Output"
logFile = "log_dim.txt"
logMask = "15"
marketDataFile = "market.txt"
fixingDataFile = "fixings.txt"
implyTodaysFixings = "N"
curveConfigFile = "runtime_policy/resolved_curve_configuration.json"
conventionsFile = "reference_registry/convention_manifest.json"
marketConfigFile = "runtime_policy/resolved_todays_market.json"
pricingEnginesFile = "runtime_policy/pricingengine/resolved_pricing_policy.json"
portfolioFile = "portfolio.xml"
observationModel = "Disable"

[markets]
lgmcalibration = "collateral_inccy"
fxcalibration = "default"
pricing = "defaut"
simulation = "default"

[analytics]
[analytics.npv]
active = "N"
baseCurrency = "EUR"
outputFileName = "npv.csv"

[analytics.cashflow]
active = "N"
outputFileName = "flows.csv"

[analytics.curves]
active = "N"
configuration = "default"
grid = "240,1M"
outputFileName = "curves.csv"

[analytics.simulation]
active = "Y"
simulationConfigFile = "runtime_policy/resolved_simulation.json"
pricingEnginesFile = "runtime_policy/pricingengine/resolved_pricing_policy.json"
baseCurrency = "EUR"
cubeFile = "stickycube.csv.gz"
aggregationScenarioDataFileName = "stickyscenariodata.csv.gz"

[analytics.xva]
active = "Y"
csaFile = "runtime_policy/resolved_netting_set_information.json"
cubeFile = "stickycube.csv.gz"
scenarioFile = "stickyscenariodata.csv.gz"
baseCurrency = "EUR"
exposureProfiles = "Y"
exposureProfilesByTrade = "Y"
quantile = "0.95"
calculationType = "NoLag"
allocationMethod = "Marginal"
marginalAllocationLimit = "1.0"
exerciseNextBreak = "N"
cva = "Y"
dva = "N"
dvaName = "BANK"
fva = "Y"
fvaBorrowingCurve = "BANK_EUR_BORROW"
fvaLendingCurve = "BANK_EUR_LEND"
colva = "Y"
collateralFloor = "Y"
dim = "Y"
mva = "Y"
dimQuantile = "0.99"
dimHorizonCalendarDays = "14"
dimRegressionOrder = "1"
dimRegressors = ""
dimLocalRegressionEvaluations = "100"
dimLocalRegressionBandwidth = "0.25"
dimScaling = "1.0"
dimEvolutionFile = "dim_evolution.csv"
dimOutputNettingSet = "CPTY_A"
dimRegressionFiles = "dim_regression.csv"
dimOutputGridPoints = "100"
